#!/usr/bin/env ruby
# encoding: utf-8

puts "Deploying environment..."

dir = Dir.pwd

dotfiles = %w[
  dotiles/profile
  dotfiles/aprc
  dotfiles/gemrc
  dotfiles/gitconfig
  dotfiles/gitignore
  dotfiles/hushlogin
  dotfiles/irbrc
  dotfiles/ruby-version
  dotfiles/tm_properties
]

system "mkdir -pv /usr/local/bin"

dotfiles.each do |file|
  target_name = file.split("/").last
  system "cp -fv #{dir}/#{file} ~/.#{target_name}"
  system "chmod -vv 750 ~/.#{target_name}"
end

system "#{dir}/deploy_local"

puts "Environment deployed ✔"
